spring:
  config:
    activate:
      on-profile: prod

lab:
  datasource:
    host: mysql
    port: 3306
    database: lab
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    host: redis
    port: 6379
    password: 123456
  mq:
    host: rabbitmq
    port: 5672
    virtualHost: /lab
    username: lab
    password: lab
  mail:
    # 配置邮件发送者用户名或者账户
    username: liangyujia1203@qq.com
    # 配置邮件发送者密码或者授权码
    password: oyysnftrdsrmhfdj